export const EVENT_NAMES = {
	AFTER_RESIZE: "afterResize",
	KEY: "key",
	MOUSE: "mouse",
	STOP: "stop",
	CONTROLLER: "controller",
	CONTROLLER_DISCONNECTED: "controllerDisconnected",
} as const;

export const CANVAS_TYPES = {
	ANY: Symbol("any"),
	DEFAULT: Symbol("default"),
	BACKGROUND: Symbol("background"),
} as const;

export const MOUSE_KEYS = {
	LEFT: 0,
	MIDDLE: 1,
	RIGHT: 2,
	PREV: 3,
	FORWARD: 4,
} as const;

export const MOUSE_TYPES = {
	DOWN: Symbol("down"),
	MOVE: Symbol("move"),
	NONE: Symbol("none"),
	UP: Symbol("up"),
} as const;

export const KEYBOARD_KEYS = {
	KEY_0: 48,
	KEY_1: 49,
	KEY_2: 50,
	KEY_3: 51,
	KEY_4: 52,
	KEY_5: 53,
	KEY_6: 54,
	KEY_7: 55,
	KEY_8: 56,
	KEY_9: 57,
	KEY_A: 65,
	KEY_B: 66,
	KEY_C: 67,
	KEY_D: 68,
	KEY_DOWN: 40,
	KEY_E: 69,
	KEY_ENTER: 13,
	KEY_ESCAPE: 27,
	KEY_F: 70,
	KEY_G: 71,
	KEY_H: 72,
	KEY_I: 73,
	KEY_J: 74,
	KEY_K: 75,
	KEY_L: 76,
	KEY_LEFT: 37,
	KEY_M: 77,
	KEY_N: 78,
	KEY_O: 79,
	KEY_P: 80,
	KEY_Q: 81,
	KEY_R: 82,
	KEY_RIGHT: 39,
	KEY_S: 83,
	KEY_SPACE: 32,
	KEY_T: 84,
	KEY_TAB: 9,
	KEY_U: 85,
	KEY_UP: 38,
	KEY_V: 86,
	KEY_W: 87,
	KEY_X: 88,
	KEY_Y: 89,
	KEY_Z: 90,
} as const;

export const CONTROLLER_KEYS = {
	A: 0,
	B: 1,
	X: 2,
	Y: 3,
	LB: 4,
	RB: 5,
	LT: 6,
	RT: 7,
	SELECT: 8,
	START: 9,
	LEFT_STICK: 10,
	RIGHT_STICK: 11,
	UP: 12,
	DOWN: 13,
	LEFT: 14,
	RIGHT: 15,
	GUIDE: 16,
} as const;
