#!/usr/bin/env node
// Generates src/index.ts by re-exporting every module under src/ except
// the exclude list. Defaults are re-aliased to their file basename
// (relying on the PascalCase-file-name = default-export-name convention).
// Invoked by scripts/build.mjs; the barrel is deleted after bundling.
//
// Because the barrel is all `export *`, two modules exporting the same name
// is a silent trap: it builds fine here but breaks downstream — a consumer's
// `import { X }` throws "conflicting star exports" and `import * as g` drops X
// with no error. So the generator collects every contributed name and aborts
// on a collision, turning that latent hazard into a loud build failure.

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src");
const OUT = join(SRC, "index.ts");

const EXCLUDE_DIRS = new Set();
const EXCLUDE_FILES = new Set(["index.ts"]);

function walk(dir) {
	const out = [];

	for (const name of readdirSync(dir).sort()) {
		const full = join(dir, name);
		const rel = relative(SRC, full);

		if (statSync(full).isDirectory()) {
			if (EXCLUDE_DIRS.has(name)) {
				continue;
			}

			out.push(...walk(full));
		} else {
			if (EXCLUDE_FILES.has(rel)) {
				continue;
			}

			if (!name.endsWith(".ts") || name.endsWith(".d.ts")) {
				continue;
			}

			out.push(rel.replace(/\\/g, "/"));
		}
	}
	return out;
}

function stripComments(src) {
	return src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
}

// Named declarations the barrel re-exports via `export *`. Deliberately does
// not match `export default …` (that name is contributed by the file basename,
// tracked separately) nor the bare `export {}` marker. A Set dedupes overload
// signatures (e.g. `generateGrid` declared several times in one module).
function namedExportNames(stripped) {
	const names = new Set();
	const re =
		/\bexport\s+(?:async\s+)?(?:abstract\s+)?(?:function|const|let|var|class|enum|namespace|interface|type)\s+([A-Za-z_$][\w$]*)/g;
	let m;
	while ((m = re.exec(stripped))) {
		names.add(m[1]);
	}
	return names;
}

function inspect(filePath) {
	const stripped = stripComments(readFileSync(filePath, "utf8"));
	const hasDefault = /\bexport\s+default\b/.test(stripped);
	// `export *`, `export {...}`, `export const|let|var|function|class|interface|type|enum|namespace`
	const hasNamed =
		/\bexport\s+(?:\*|\{|const|let|var|function|class|interface|type|enum|namespace|abstract|async)\b/.test(
			stripped,
		);

	return { hasDefault, hasNamed, names: namedExportNames(stripped) };
}

const files = walk(SRC);
const lines = ["// generated by scripts/generate-barrel.mjs — do not edit", ""];
// name -> modules contributing it, to catch collisions across `export *`.
const contributors = new Map();

function contribute(name, rel) {
	if (!contributors.has(name)) {
		contributors.set(name, []);
	}
	contributors.get(name).push(rel);
}

let lastDir = "";
for (const rel of files) {
	const dir = rel.includes("/") ? rel.split("/")[0] : ".";
	if (dir !== lastDir) {
		if (lastDir) {
			lines.push("");
		}
		lines.push(`// ${dir}`);
		lastDir = dir;
	}

	const base = rel.replace(/\.ts$/, "");
	const name = base.split("/").pop();
	const importPath = `./${base}`;
	const { hasDefault, hasNamed, names } = inspect(join(SRC, rel));

	if (hasDefault) {
		lines.push(`export { default as ${name} } from "${importPath}";`);
		contribute(name, rel);
	}

	if (hasNamed) {
		lines.push(`export * from "${importPath}";`);
		names.forEach(n => contribute(n, rel));
	}
}

const collisions = [...contributors].filter(([, mods]) => mods.length > 1);
if (collisions.length) {
	const detail = collisions
		.map(([name, mods]) => `  "${name}" exported by: ${mods.join(", ")}`)
		.join("\n");
	console.error(
		`generate-barrel: duplicate export name(s) across modules — the barrel's ` +
			`\`export *\` would drop these silently and break consumers:\n${detail}`,
	);
	process.exit(1);
}

writeFileSync(OUT, lines.join("\n") + "\n", "utf8");
console.log(`generated ${OUT} (${files.length} modules)`);
