#!/usr/bin/env node
// Generates src/index.ts by re-exporting every module under src/ except
// the exclude list. Defaults are re-aliased to their file basename
// (relying on the PascalCase-file-name = default-export-name convention).
// Run before `tsc` via the `prebuild` npm script.

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(import.meta.url), "../..");
const SRC = join(ROOT, "src");
const OUT = join(SRC, "index.ts");

const EXCLUDE_DIRS = new Set(["prototypes"]);
const EXCLUDE_FILES = new Set(["index.ts", "index.d.ts"]);

function walk(dir) {
	const out = [];
	for (const name of readdirSync(dir).sort()) {
		const full = join(dir, name);
		const rel = relative(SRC, full);
		if (statSync(full).isDirectory()) {
			if (EXCLUDE_DIRS.has(name)) continue;
			out.push(...walk(full));
		} else {
			if (EXCLUDE_FILES.has(rel)) continue;
			if (!name.endsWith(".ts") || name.endsWith(".d.ts")) continue;
			out.push(rel);
		}
	}
	return out;
}

function stripComments(src) {
	return src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
}

function inspect(filePath) {
	const stripped = stripComments(readFileSync(filePath, "utf8"));
	const hasDefault = /\bexport\s+default\b/.test(stripped);
	// `export *`, `export {...}`, `export const|let|var|function|class|interface|type|enum|namespace`
	const hasNamed =
		/\bexport\s+(?:\*|\{|const|let|var|function|class|interface|type|enum|namespace|abstract|async)\b/.test(
			stripped,
		);
	return { hasDefault, hasNamed };
}

const files = walk(SRC);
const lines = ["// generated by scripts/generate-barrel.mjs — do not edit", ""];

let lastDir = "";
for (const rel of files) {
	const dir = rel.includes("/") ? rel.split("/")[0] : ".";
	if (dir !== lastDir) {
		if (lastDir) lines.push("");
		lines.push(`// ${dir}`);
		lastDir = dir;
	}
	const base = rel.replace(/\.ts$/, "");
	const name = base.split("/").pop();
	const importPath = `./${base}`;
	const { hasDefault, hasNamed } = inspect(join(SRC, rel));
	if (hasDefault) {
		lines.push(`export { default as ${name} } from "${importPath}";`);
	}
	if (hasNamed) {
		lines.push(`export * from "${importPath}";`);
	}
}

writeFileSync(OUT, lines.join("\n") + "\n", "utf8");
console.log(`generated ${OUT} (${files.length} modules)`);
